---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: default.yml
  when: newrelic_loaded_os_family|default(False) == False

- name: "Install Newrelic license key"
  lineinfile: dest=/etc/newrelic/nrsysmond.cfg
              state=present
              regexp="license_key=REPLACE_WITH_REAL_KEY"
              line="license_key={{ newrelic_licence_key }}"
  notify:
    - Restart New Relic
  when: newrelic_loaded_os_family|default(False) != False

- name: Ensure New Relic Sysmond is started and enabled
  service:
    name: newrelic-sysmond
    state: started
    enabled: yes
